package dk.bitmovers.timeregistration.model;

// Generated May 3, 2015 11:09:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private int id;
	private User user;
	private String name;
	private Date created;
	private Set<ClientProject> clientProjects = new HashSet<ClientProject>(0);

	public Client() {
	}

	public Client(int id, User user, String name, Date created) {
		this.id = id;
		this.user = user;
		this.name = name;
		this.created = created;
	}

	public Client(int id, User user, String name, Date created,
			Set<ClientProject> clientProjects) {
		this.id = id;
		this.user = user;
		this.name = name;
		this.created = created;
		this.clientProjects = clientProjects;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Set<ClientProject> getClientProjects() {
		return this.clientProjects;
	}

	public void setClientProjects(Set<ClientProject> clientProjects) {
		this.clientProjects = clientProjects;
	}

}
