package dk.bitmovers.timeregistration.model;

// Generated May 3, 2015 11:09:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProviderAccount generated by hbm2java
 */
public class ProviderAccount implements java.io.Serializable {

	private int id;
	private Provider provider;
	private User user;
	private Date created;
	private String code;
	private String name;
	private String isActive;
	private Set<RegistrationItem> registrationItems = new HashSet<RegistrationItem>(
			0);

	public ProviderAccount() {
	}

	public ProviderAccount(int id, Provider provider, User user, Date created,
			String code, String name, String isActive) {
		this.id = id;
		this.provider = provider;
		this.user = user;
		this.created = created;
		this.code = code;
		this.name = name;
		this.isActive = isActive;
	}

	public ProviderAccount(int id, Provider provider, User user, Date created,
			String code, String name, String isActive,
			Set<RegistrationItem> registrationItems) {
		this.id = id;
		this.provider = provider;
		this.user = user;
		this.created = created;
		this.code = code;
		this.name = name;
		this.isActive = isActive;
		this.registrationItems = registrationItems;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Provider getProvider() {
		return this.provider;
	}

	public void setProvider(Provider provider) {
		this.provider = provider;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public Set<RegistrationItem> getRegistrationItems() {
		return this.registrationItems;
	}

	public void setRegistrationItems(Set<RegistrationItem> registrationItems) {
		this.registrationItems = registrationItems;
	}

}
