package dk.bitmovers.timeregistration.model;

// Generated May 3, 2015 11:09:22 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * RegistrationSubmitted generated by hbm2java
 */
public class RegistrationSubmitted implements java.io.Serializable {

	private int id;
	private RegistrationItem registrationItem;
	private User user;
	private Date created;
	private BigDecimal amount;
	private String comments;

	public RegistrationSubmitted() {
	}

	public RegistrationSubmitted(int id, RegistrationItem registrationItem,
			User user, Date created, BigDecimal amount) {
		this.id = id;
		this.registrationItem = registrationItem;
		this.user = user;
		this.created = created;
		this.amount = amount;
	}

	public RegistrationSubmitted(int id, RegistrationItem registrationItem,
			User user, Date created, BigDecimal amount, String comments) {
		this.id = id;
		this.registrationItem = registrationItem;
		this.user = user;
		this.created = created;
		this.amount = amount;
		this.comments = comments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public RegistrationItem getRegistrationItem() {
		return this.registrationItem;
	}

	public void setRegistrationItem(RegistrationItem registrationItem) {
		this.registrationItem = registrationItem;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
