package dk.bitmovers.timeregistration.model;

// Generated May 3, 2015 11:09:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int id;
	private Date created;
	private String role;
	private Set<UserRoleLink> userRoleLinks = new HashSet<UserRoleLink>(0);

	public Role() {
	}

	public Role(int id, Date created, String role) {
		this.id = id;
		this.created = created;
		this.role = role;
	}

	public Role(int id, Date created, String role,
			Set<UserRoleLink> userRoleLinks) {
		this.id = id;
		this.created = created;
		this.role = role;
		this.userRoleLinks = userRoleLinks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set<UserRoleLink> getUserRoleLinks() {
		return this.userRoleLinks;
	}

	public void setUserRoleLinks(Set<UserRoleLink> userRoleLinks) {
		this.userRoleLinks = userRoleLinks;
	}

}
