package dk.bitmovers.timeregistration.model;

// Generated May 3, 2015 11:09:22 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UserPassword generated by hbm2java
 */
public class UserPassword implements java.io.Serializable {

	private int id;
	private User user;
	private Date created;
	private String isActive;
	private Date ended;
	private String password;

	public UserPassword() {
	}

	public UserPassword(int id, User user, Date created, String isActive,
			String password) {
		this.id = id;
		this.user = user;
		this.created = created;
		this.isActive = isActive;
		this.password = password;
	}

	public UserPassword(int id, User user, Date created, String isActive,
			Date ended, String password) {
		this.id = id;
		this.user = user;
		this.created = created;
		this.isActive = isActive;
		this.ended = ended;
		this.password = password;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public Date getEnded() {
		return this.ended;
	}

	public void setEnded(Date ended) {
		this.ended = ended;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
