package dk.bitmovers.timeregistration.model;

// Generated May 3, 2015 11:09:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private Date created;
	private String login;
	private String name;
	private String isLoginEnabled;
	private byte enabled;
	private Set<RegistrationSubmitted> registrationSubmitteds = new HashSet<RegistrationSubmitted>(
			0);
	private Set<Client> clients = new HashSet<Client>(0);
	private Set<ProviderAccount> providerAccounts = new HashSet<ProviderAccount>(
			0);
	private Set<WorkClockEvent> workClockEvents = new HashSet<WorkClockEvent>(0);
	private Set<Provider> providers = new HashSet<Provider>(0);
	private Set<RegistrationEvent> registrationEvents = new HashSet<RegistrationEvent>(
			0);
	private Set<RegistrationItem> registrationItems = new HashSet<RegistrationItem>(
			0);
	private Set<UserRoleLink> userRoleLinks = new HashSet<UserRoleLink>(0);
	private Set<UserPassword> userPasswords = new HashSet<UserPassword>(0);
	private Set<ClientProject> clientProjects = new HashSet<ClientProject>(0);

	public User() {
	}

	public User(int id, Date created, String login, String isLoginEnabled,
			byte enabled) {
		this.id = id;
		this.created = created;
		this.login = login;
		this.isLoginEnabled = isLoginEnabled;
		this.enabled = enabled;
	}

	public User(int id, Date created, String login, String name,
			String isLoginEnabled, byte enabled,
			Set<RegistrationSubmitted> registrationSubmitteds,
			Set<Client> clients, Set<ProviderAccount> providerAccounts,
			Set<WorkClockEvent> workClockEvents, Set<Provider> providers,
			Set<RegistrationEvent> registrationEvents,
			Set<RegistrationItem> registrationItems,
			Set<UserRoleLink> userRoleLinks, Set<UserPassword> userPasswords,
			Set<ClientProject> clientProjects) {
		this.id = id;
		this.created = created;
		this.login = login;
		this.name = name;
		this.isLoginEnabled = isLoginEnabled;
		this.enabled = enabled;
		this.registrationSubmitteds = registrationSubmitteds;
		this.clients = clients;
		this.providerAccounts = providerAccounts;
		this.workClockEvents = workClockEvents;
		this.providers = providers;
		this.registrationEvents = registrationEvents;
		this.registrationItems = registrationItems;
		this.userRoleLinks = userRoleLinks;
		this.userPasswords = userPasswords;
		this.clientProjects = clientProjects;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIsLoginEnabled() {
		return this.isLoginEnabled;
	}

	public void setIsLoginEnabled(String isLoginEnabled) {
		this.isLoginEnabled = isLoginEnabled;
	}

	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	public Set<RegistrationSubmitted> getRegistrationSubmitteds() {
		return this.registrationSubmitteds;
	}

	public void setRegistrationSubmitteds(
			Set<RegistrationSubmitted> registrationSubmitteds) {
		this.registrationSubmitteds = registrationSubmitteds;
	}

	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	public Set<ProviderAccount> getProviderAccounts() {
		return this.providerAccounts;
	}

	public void setProviderAccounts(Set<ProviderAccount> providerAccounts) {
		this.providerAccounts = providerAccounts;
	}

	public Set<WorkClockEvent> getWorkClockEvents() {
		return this.workClockEvents;
	}

	public void setWorkClockEvents(Set<WorkClockEvent> workClockEvents) {
		this.workClockEvents = workClockEvents;
	}

	public Set<Provider> getProviders() {
		return this.providers;
	}

	public void setProviders(Set<Provider> providers) {
		this.providers = providers;
	}

	public Set<RegistrationEvent> getRegistrationEvents() {
		return this.registrationEvents;
	}

	public void setRegistrationEvents(Set<RegistrationEvent> registrationEvents) {
		this.registrationEvents = registrationEvents;
	}

	public Set<RegistrationItem> getRegistrationItems() {
		return this.registrationItems;
	}

	public void setRegistrationItems(Set<RegistrationItem> registrationItems) {
		this.registrationItems = registrationItems;
	}

	public Set<UserRoleLink> getUserRoleLinks() {
		return this.userRoleLinks;
	}

	public void setUserRoleLinks(Set<UserRoleLink> userRoleLinks) {
		this.userRoleLinks = userRoleLinks;
	}

	public Set<UserPassword> getUserPasswords() {
		return this.userPasswords;
	}

	public void setUserPasswords(Set<UserPassword> userPasswords) {
		this.userPasswords = userPasswords;
	}

	public Set<ClientProject> getClientProjects() {
		return this.clientProjects;
	}

	public void setClientProjects(Set<ClientProject> clientProjects) {
		this.clientProjects = clientProjects;
	}

}
