package dk.bitmovers.timeregistration.model;

// Generated May 3, 2015 11:09:22 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UserRoleLink generated by hbm2java
 */
public class UserRoleLink implements java.io.Serializable {

	private int id;
	private Role role;
	private User user;
	private Date created;
	private Date ended;
	private String isActive;

	public UserRoleLink() {
	}

	public UserRoleLink(int id, Role role, User user, Date created,
			String isActive) {
		this.id = id;
		this.role = role;
		this.user = user;
		this.created = created;
		this.isActive = isActive;
	}

	public UserRoleLink(int id, Role role, User user, Date created, Date ended,
			String isActive) {
		this.id = id;
		this.role = role;
		this.user = user;
		this.created = created;
		this.ended = ended;
		this.isActive = isActive;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getEnded() {
		return this.ended;
	}

	public void setEnded(Date ended) {
		this.ended = ended;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

}
