package dk.bitmovers.timeregistration.model;

// Generated May 3, 2015 11:09:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkClockEventType generated by hbm2java
 */
public class WorkClockEventType implements java.io.Serializable {

	private int id;
	private Date created;
	private String eventType;
	private Set<WorkClockEvent> workClockEvents = new HashSet<WorkClockEvent>(0);

	public WorkClockEventType() {
	}

	public WorkClockEventType(int id, Date created, String eventType) {
		this.id = id;
		this.created = created;
		this.eventType = eventType;
	}

	public WorkClockEventType(int id, Date created, String eventType,
			Set<WorkClockEvent> workClockEvents) {
		this.id = id;
		this.created = created;
		this.eventType = eventType;
		this.workClockEvents = workClockEvents;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	public Set<WorkClockEvent> getWorkClockEvents() {
		return this.workClockEvents;
	}

	public void setWorkClockEvents(Set<WorkClockEvent> workClockEvents) {
		this.workClockEvents = workClockEvents;
	}

}
