package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClientCode generated by hbm2java
 */
public class ClientCode implements java.io.Serializable {

	private int id;
	private Client client;
	private Date created;
	private String code;
	private String name;
	private Set registrationItems = new HashSet(0);
	private Set userClientCodeLinks = new HashSet(0);

	public ClientCode() {
	}

	public ClientCode(Client client, Date created, String code, String name) {
		this.client = client;
		this.created = created;
		this.code = code;
		this.name = name;
	}

	public ClientCode(Client client, Date created, String code, String name,
			Set registrationItems, Set userClientCodeLinks) {
		this.client = client;
		this.created = created;
		this.code = code;
		this.name = name;
		this.registrationItems = registrationItems;
		this.userClientCodeLinks = userClientCodeLinks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getRegistrationItems() {
		return this.registrationItems;
	}

	public void setRegistrationItems(Set registrationItems) {
		this.registrationItems = registrationItems;
	}

	public Set getUserClientCodeLinks() {
		return this.userClientCodeLinks;
	}

	public void setUserClientCodeLinks(Set userClientCodeLinks) {
		this.userClientCodeLinks = userClientCodeLinks;
	}

}
