package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Password generated by hbm2java
 */
public class Password implements java.io.Serializable {

	private int id;
	private Date created;
	private String password;
	private Set userPasswordLinks = new HashSet(0);

	public Password() {
	}

	public Password(Date created, String password) {
		this.created = created;
		this.password = password;
	}

	public Password(Date created, String password, Set userPasswordLinks) {
		this.created = created;
		this.password = password;
		this.userPasswordLinks = userPasswordLinks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getUserPasswordLinks() {
		return this.userPasswordLinks;
	}

	public void setUserPasswordLinks(Set userPasswordLinks) {
		this.userPasswordLinks = userPasswordLinks;
	}

}
