package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Provider generated by hbm2java
 */
public class Provider implements java.io.Serializable {

	private int id;
	private String name;
	private Date created;
	private Set providerCodes = new HashSet(0);

	public Provider() {
	}

	public Provider(String name, Date created) {
		this.name = name;
		this.created = created;
	}

	public Provider(String name, Date created, Set providerCodes) {
		this.name = name;
		this.created = created;
		this.providerCodes = providerCodes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Set getProviderCodes() {
		return this.providerCodes;
	}

	public void setProviderCodes(Set providerCodes) {
		this.providerCodes = providerCodes;
	}

}
