package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProviderCode generated by hbm2java
 */
public class ProviderCode implements java.io.Serializable {

	private int id;
	private Provider provider;
	private Date created;
	private String code;
	private String name;
	private Set userProviderCodeLinks = new HashSet(0);
	private Set registrationItems = new HashSet(0);

	public ProviderCode() {
	}

	public ProviderCode(Provider provider, Date created, String code,
			String name) {
		this.provider = provider;
		this.created = created;
		this.code = code;
		this.name = name;
	}

	public ProviderCode(Provider provider, Date created, String code,
			String name, Set userProviderCodeLinks, Set registrationItems) {
		this.provider = provider;
		this.created = created;
		this.code = code;
		this.name = name;
		this.userProviderCodeLinks = userProviderCodeLinks;
		this.registrationItems = registrationItems;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Provider getProvider() {
		return this.provider;
	}

	public void setProvider(Provider provider) {
		this.provider = provider;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUserProviderCodeLinks() {
		return this.userProviderCodeLinks;
	}

	public void setUserProviderCodeLinks(Set userProviderCodeLinks) {
		this.userProviderCodeLinks = userProviderCodeLinks;
	}

	public Set getRegistrationItems() {
		return this.registrationItems;
	}

	public void setRegistrationItems(Set registrationItems) {
		this.registrationItems = registrationItems;
	}

}
