package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * RegistrationEvent generated by hbm2java
 */
public class RegistrationEvent implements java.io.Serializable {

	private int id;
	private RegistrationItem registrationItem;
	private User user;
	private Date created;
	private Date eventTime;
	private String comments;

	public RegistrationEvent() {
	}

	public RegistrationEvent(RegistrationItem registrationItem, User user,
			Date created, Date eventTime, String comments) {
		this.registrationItem = registrationItem;
		this.user = user;
		this.created = created;
		this.eventTime = eventTime;
		this.comments = comments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public RegistrationItem getRegistrationItem() {
		return this.registrationItem;
	}

	public void setRegistrationItem(RegistrationItem registrationItem) {
		this.registrationItem = registrationItem;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
