package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RegistrationItem generated by hbm2java
 */
public class RegistrationItem implements java.io.Serializable {

	private int id;
	private ClientCode clientCode;
	private ProviderCode providerCode;
	private Date created;
	private Date ended;
	private String projectName;
	private String itemName;
	private Set registrationSubmitteds = new HashSet(0);
	private Set userRegistrationItemLinks = new HashSet(0);
	private Set registrationEvents = new HashSet(0);

	public RegistrationItem() {
	}

	public RegistrationItem(ProviderCode providerCode, Date created,
			Date ended, String projectName, String itemName) {
		this.providerCode = providerCode;
		this.created = created;
		this.ended = ended;
		this.projectName = projectName;
		this.itemName = itemName;
	}

	public RegistrationItem(ClientCode clientCode, ProviderCode providerCode,
			Date created, Date ended, String projectName, String itemName,
			Set registrationSubmitteds, Set userRegistrationItemLinks,
			Set registrationEvents) {
		this.clientCode = clientCode;
		this.providerCode = providerCode;
		this.created = created;
		this.ended = ended;
		this.projectName = projectName;
		this.itemName = itemName;
		this.registrationSubmitteds = registrationSubmitteds;
		this.userRegistrationItemLinks = userRegistrationItemLinks;
		this.registrationEvents = registrationEvents;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ClientCode getClientCode() {
		return this.clientCode;
	}

	public void setClientCode(ClientCode clientCode) {
		this.clientCode = clientCode;
	}

	public ProviderCode getProviderCode() {
		return this.providerCode;
	}

	public void setProviderCode(ProviderCode providerCode) {
		this.providerCode = providerCode;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getEnded() {
		return this.ended;
	}

	public void setEnded(Date ended) {
		this.ended = ended;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Set getRegistrationSubmitteds() {
		return this.registrationSubmitteds;
	}

	public void setRegistrationSubmitteds(Set registrationSubmitteds) {
		this.registrationSubmitteds = registrationSubmitteds;
	}

	public Set getUserRegistrationItemLinks() {
		return this.userRegistrationItemLinks;
	}

	public void setUserRegistrationItemLinks(Set userRegistrationItemLinks) {
		this.userRegistrationItemLinks = userRegistrationItemLinks;
	}

	public Set getRegistrationEvents() {
		return this.registrationEvents;
	}

	public void setRegistrationEvents(Set registrationEvents) {
		this.registrationEvents = registrationEvents;
	}

}
