package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int id;
	private Date created;
	private String role;
	private Set userRoleLinks = new HashSet(0);

	public Role() {
	}

	public Role(Date created, String role) {
		this.created = created;
		this.role = role;
	}

	public Role(Date created, String role, Set userRoleLinks) {
		this.created = created;
		this.role = role;
		this.userRoleLinks = userRoleLinks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set getUserRoleLinks() {
		return this.userRoleLinks;
	}

	public void setUserRoleLinks(Set userRoleLinks) {
		this.userRoleLinks = userRoleLinks;
	}

}
