package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private Date created;
	private String login;
	private String name;
	private String isLoginEnabled;
	private boolean enabled;
	private Set userPasswordLinks = new HashSet(0);
	private Set registrationSubmitteds = new HashSet(0);
	private Set userProviderCodeLinks = new HashSet(0);
	private Set registrationEvents = new HashSet(0);
	private Set userClientCodeLinks = new HashSet(0);
	private Set userRoleLinks = new HashSet(0);
	private Set userRegistrationItemLinks = new HashSet(0);

	public User() {
	}

	public User(Date created, String login, String isLoginEnabled,
			boolean enabled) {
		this.created = created;
		this.login = login;
		this.isLoginEnabled = isLoginEnabled;
		this.enabled = enabled;
	}

	public User(Date created, String login, String name, String isLoginEnabled,
			boolean enabled, Set userPasswordLinks, Set registrationSubmitteds,
			Set userProviderCodeLinks, Set registrationEvents,
			Set userClientCodeLinks, Set userRoleLinks,
			Set userRegistrationItemLinks) {
		this.created = created;
		this.login = login;
		this.name = name;
		this.isLoginEnabled = isLoginEnabled;
		this.enabled = enabled;
		this.userPasswordLinks = userPasswordLinks;
		this.registrationSubmitteds = registrationSubmitteds;
		this.userProviderCodeLinks = userProviderCodeLinks;
		this.registrationEvents = registrationEvents;
		this.userClientCodeLinks = userClientCodeLinks;
		this.userRoleLinks = userRoleLinks;
		this.userRegistrationItemLinks = userRegistrationItemLinks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIsLoginEnabled() {
		return this.isLoginEnabled;
	}

	public void setIsLoginEnabled(String isLoginEnabled) {
		this.isLoginEnabled = isLoginEnabled;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set getUserPasswordLinks() {
		return this.userPasswordLinks;
	}

	public void setUserPasswordLinks(Set userPasswordLinks) {
		this.userPasswordLinks = userPasswordLinks;
	}

	public Set getRegistrationSubmitteds() {
		return this.registrationSubmitteds;
	}

	public void setRegistrationSubmitteds(Set registrationSubmitteds) {
		this.registrationSubmitteds = registrationSubmitteds;
	}

	public Set getUserProviderCodeLinks() {
		return this.userProviderCodeLinks;
	}

	public void setUserProviderCodeLinks(Set userProviderCodeLinks) {
		this.userProviderCodeLinks = userProviderCodeLinks;
	}

	public Set getRegistrationEvents() {
		return this.registrationEvents;
	}

	public void setRegistrationEvents(Set registrationEvents) {
		this.registrationEvents = registrationEvents;
	}

	public Set getUserClientCodeLinks() {
		return this.userClientCodeLinks;
	}

	public void setUserClientCodeLinks(Set userClientCodeLinks) {
		this.userClientCodeLinks = userClientCodeLinks;
	}

	public Set getUserRoleLinks() {
		return this.userRoleLinks;
	}

	public void setUserRoleLinks(Set userRoleLinks) {
		this.userRoleLinks = userRoleLinks;
	}

	public Set getUserRegistrationItemLinks() {
		return this.userRegistrationItemLinks;
	}

	public void setUserRegistrationItemLinks(Set userRegistrationItemLinks) {
		this.userRegistrationItemLinks = userRegistrationItemLinks;
	}

}
