package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UserRoleLink generated by hbm2java
 */
public class UserRoleLink implements java.io.Serializable {

	private int id;
	private Role role;
	private User user;
	private Date created;
	private Date ended;

	public UserRoleLink() {
	}

	public UserRoleLink(Role role, User user, Date created, Date ended) {
		this.role = role;
		this.user = user;
		this.created = created;
		this.ended = ended;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getEnded() {
		return this.ended;
	}

	public void setEnded(Date ended) {
		this.ended = ended;
	}

}
