package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UserClientCodeLink generated by hbm2java
 */
public class UserClientCodeLink implements java.io.Serializable {

	private int id;
	private ClientCode clientCode;
	private User user;
	private Date created;
	private Date ended;

	public UserClientCodeLink() {
	}

	public UserClientCodeLink(ClientCode clientCode, User user, Date created,
			Date ended) {
		this.clientCode = clientCode;
		this.user = user;
		this.created = created;
		this.ended = ended;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ClientCode getClientCode() {
		return this.clientCode;
	}

	public void setClientCode(ClientCode clientCode) {
		this.clientCode = clientCode;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getEnded() {
		return this.ended;
	}

	public void setEnded(Date ended) {
		this.ended = ended;
	}

}
