package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwClientCode generated by hbm2java
 */
public class VwClientCode implements java.io.Serializable {

	private VwClientCodeId id;

	public VwClientCode() {
	}

	public VwClientCode(VwClientCodeId id) {
		this.id = id;
	}

	public VwClientCodeId getId() {
		return this.id;
	}

	public void setId(VwClientCodeId id) {
		this.id = id;
	}

}
