package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwClientCodeId generated by hbm2java
 */
public class VwClientCodeId implements java.io.Serializable {

	private int clientId;
	private String clientName;
	private String clientCode;
	private String clientCodeName;
	private int clientCodeId;

	public VwClientCodeId() {
	}

	public VwClientCodeId(int clientId, String clientName, String clientCode,
			String clientCodeName, int clientCodeId) {
		this.clientId = clientId;
		this.clientName = clientName;
		this.clientCode = clientCode;
		this.clientCodeName = clientCodeName;
		this.clientCodeId = clientCodeId;
	}

	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getClientCode() {
		return this.clientCode;
	}

	public void setClientCode(String clientCode) {
		this.clientCode = clientCode;
	}

	public String getClientCodeName() {
		return this.clientCodeName;
	}

	public void setClientCodeName(String clientCodeName) {
		this.clientCodeName = clientCodeName;
	}

	public int getClientCodeId() {
		return this.clientCodeId;
	}

	public void setClientCodeId(int clientCodeId) {
		this.clientCodeId = clientCodeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwClientCodeId))
			return false;
		VwClientCodeId castOther = (VwClientCodeId) other;

		return (this.getClientId() == castOther.getClientId())
				&& ((this.getClientName() == castOther.getClientName()) || (this
						.getClientName() != null
						&& castOther.getClientName() != null && this
						.getClientName().equals(castOther.getClientName())))
				&& ((this.getClientCode() == castOther.getClientCode()) || (this
						.getClientCode() != null
						&& castOther.getClientCode() != null && this
						.getClientCode().equals(castOther.getClientCode())))
				&& ((this.getClientCodeName() == castOther.getClientCodeName()) || (this
						.getClientCodeName() != null
						&& castOther.getClientCodeName() != null && this
						.getClientCodeName().equals(
								castOther.getClientCodeName())))
				&& (this.getClientCodeId() == castOther.getClientCodeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClientId();
		result = 37
				* result
				+ (getClientName() == null ? 0 : this.getClientName()
						.hashCode());
		result = 37
				* result
				+ (getClientCode() == null ? 0 : this.getClientCode()
						.hashCode());
		result = 37
				* result
				+ (getClientCodeName() == null ? 0 : this.getClientCodeName()
						.hashCode());
		result = 37 * result + this.getClientCodeId();
		return result;
	}

}
