package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwProviderCode generated by hbm2java
 */
public class VwProviderCode implements java.io.Serializable {

	private VwProviderCodeId id;

	public VwProviderCode() {
	}

	public VwProviderCode(VwProviderCodeId id) {
		this.id = id;
	}

	public VwProviderCodeId getId() {
		return this.id;
	}

	public void setId(VwProviderCodeId id) {
		this.id = id;
	}

}
