package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * VwUserPasswordId generated by hbm2java
 */
public class VwUserPasswordId implements java.io.Serializable {

	private String password;
	private Date passwordCreated;
	private int userId;
	private Date userCreated;
	private String login;
	private String name;
	private Date linkCreated;
	private Date linkEnded;

	public VwUserPasswordId() {
	}

	public VwUserPasswordId(String password, Date passwordCreated, int userId,
			Date userCreated, String login, Date linkCreated, Date linkEnded) {
		this.password = password;
		this.passwordCreated = passwordCreated;
		this.userId = userId;
		this.userCreated = userCreated;
		this.login = login;
		this.linkCreated = linkCreated;
		this.linkEnded = linkEnded;
	}

	public VwUserPasswordId(String password, Date passwordCreated, int userId,
			Date userCreated, String login, String name, Date linkCreated,
			Date linkEnded) {
		this.password = password;
		this.passwordCreated = passwordCreated;
		this.userId = userId;
		this.userCreated = userCreated;
		this.login = login;
		this.name = name;
		this.linkCreated = linkCreated;
		this.linkEnded = linkEnded;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getPasswordCreated() {
		return this.passwordCreated;
	}

	public void setPasswordCreated(Date passwordCreated) {
		this.passwordCreated = passwordCreated;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getUserCreated() {
		return this.userCreated;
	}

	public void setUserCreated(Date userCreated) {
		this.userCreated = userCreated;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getLinkCreated() {
		return this.linkCreated;
	}

	public void setLinkCreated(Date linkCreated) {
		this.linkCreated = linkCreated;
	}

	public Date getLinkEnded() {
		return this.linkEnded;
	}

	public void setLinkEnded(Date linkEnded) {
		this.linkEnded = linkEnded;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwUserPasswordId))
			return false;
		VwUserPasswordId castOther = (VwUserPasswordId) other;

		return ((this.getPassword() == castOther.getPassword()) || (this
				.getPassword() != null && castOther.getPassword() != null && this
				.getPassword().equals(castOther.getPassword())))
				&& ((this.getPasswordCreated() == castOther
						.getPasswordCreated()) || (this.getPasswordCreated() != null
						&& castOther.getPasswordCreated() != null && this
						.getPasswordCreated().equals(
								castOther.getPasswordCreated())))
				&& (this.getUserId() == castOther.getUserId())
				&& ((this.getUserCreated() == castOther.getUserCreated()) || (this
						.getUserCreated() != null
						&& castOther.getUserCreated() != null && this
						.getUserCreated().equals(castOther.getUserCreated())))
				&& ((this.getLogin() == castOther.getLogin()) || (this
						.getLogin() != null && castOther.getLogin() != null && this
						.getLogin().equals(castOther.getLogin())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getLinkCreated() == castOther.getLinkCreated()) || (this
						.getLinkCreated() != null
						&& castOther.getLinkCreated() != null && this
						.getLinkCreated().equals(castOther.getLinkCreated())))
				&& ((this.getLinkEnded() == castOther.getLinkEnded()) || (this
						.getLinkEnded() != null
						&& castOther.getLinkEnded() != null && this
						.getLinkEnded().equals(castOther.getLinkEnded())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37
				* result
				+ (getPasswordCreated() == null ? 0 : this.getPasswordCreated()
						.hashCode());
		result = 37 * result + this.getUserId();
		result = 37
				* result
				+ (getUserCreated() == null ? 0 : this.getUserCreated()
						.hashCode());
		result = 37 * result
				+ (getLogin() == null ? 0 : this.getLogin().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getLinkCreated() == null ? 0 : this.getLinkCreated()
						.hashCode());
		result = 37 * result
				+ (getLinkEnded() == null ? 0 : this.getLinkEnded().hashCode());
		return result;
	}

}
