package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwUserRegistrationEvent generated by hbm2java
 */
public class VwUserRegistrationEvent implements java.io.Serializable {

	private VwUserRegistrationEventId id;

	public VwUserRegistrationEvent() {
	}

	public VwUserRegistrationEvent(VwUserRegistrationEventId id) {
		this.id = id;
	}

	public VwUserRegistrationEventId getId() {
		return this.id;
	}

	public void setId(VwUserRegistrationEventId id) {
		this.id = id;
	}

}
