package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwUserRegistrationItem generated by hbm2java
 */
public class VwUserRegistrationItem implements java.io.Serializable {

	private VwUserRegistrationItemId id;

	public VwUserRegistrationItem() {
	}

	public VwUserRegistrationItem(VwUserRegistrationItemId id) {
		this.id = id;
	}

	public VwUserRegistrationItemId getId() {
		return this.id;
	}

	public void setId(VwUserRegistrationItemId id) {
		this.id = id;
	}

}
