package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwUserPassword generated by hbm2java
 */
public class VwUserPassword implements java.io.Serializable {

	private VwUserPasswordId id;

	public VwUserPassword() {
	}

	public VwUserPassword(VwUserPasswordId id) {
		this.id = id;
	}

	public VwUserPasswordId getId() {
		return this.id;
	}

	public void setId(VwUserPasswordId id) {
		this.id = id;
	}

}
