package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwUserRole generated by hbm2java
 */
public class VwUserRole implements java.io.Serializable {

	private VwUserRoleId id;

	public VwUserRole() {
	}

	public VwUserRole(VwUserRoleId id) {
		this.id = id;
	}

	public VwUserRoleId getId() {
		return this.id;
	}

	public void setId(VwUserRoleId id) {
		this.id = id;
	}

}
