package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwUserRegistrationSubmitted generated by hbm2java
 */
public class VwUserRegistrationSubmitted implements java.io.Serializable {

	private VwUserRegistrationSubmittedId id;

	public VwUserRegistrationSubmitted() {
	}

	public VwUserRegistrationSubmitted(VwUserRegistrationSubmittedId id) {
		this.id = id;
	}

	public VwUserRegistrationSubmittedId getId() {
		return this.id;
	}

	public void setId(VwUserRegistrationSubmittedId id) {
		this.id = id;
	}

}
