package dk.schioler.tools.timeregistration.hibernate.pojo;

// Generated 03-04-2015 09:48:14 by Hibernate Tools 4.3.1

/**
 * VwUserRegistrationItemId generated by hbm2java
 */
public class VwUserRegistrationItemId implements java.io.Serializable {

	private int userId;
	private String userLogin;
	private int itemId;
	private String itemProjectName;
	private String itemItemName;
	private String clientName;
	private String clientCode;
	private String clientCodeName;
	private String providerName;
	private String providerCode;
	private String providerCodeName;

	public VwUserRegistrationItemId() {
	}

	public VwUserRegistrationItemId(int userId, String userLogin, int itemId,
			String itemProjectName, String itemItemName, String clientName,
			String clientCode, String clientCodeName, String providerName,
			String providerCode, String providerCodeName) {
		this.userId = userId;
		this.userLogin = userLogin;
		this.itemId = itemId;
		this.itemProjectName = itemProjectName;
		this.itemItemName = itemItemName;
		this.clientName = clientName;
		this.clientCode = clientCode;
		this.clientCodeName = clientCodeName;
		this.providerName = providerName;
		this.providerCode = providerCode;
		this.providerCodeName = providerCodeName;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public String getItemProjectName() {
		return this.itemProjectName;
	}

	public void setItemProjectName(String itemProjectName) {
		this.itemProjectName = itemProjectName;
	}

	public String getItemItemName() {
		return this.itemItemName;
	}

	public void setItemItemName(String itemItemName) {
		this.itemItemName = itemItemName;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getClientCode() {
		return this.clientCode;
	}

	public void setClientCode(String clientCode) {
		this.clientCode = clientCode;
	}

	public String getClientCodeName() {
		return this.clientCodeName;
	}

	public void setClientCodeName(String clientCodeName) {
		this.clientCodeName = clientCodeName;
	}

	public String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	public String getProviderCode() {
		return this.providerCode;
	}

	public void setProviderCode(String providerCode) {
		this.providerCode = providerCode;
	}

	public String getProviderCodeName() {
		return this.providerCodeName;
	}

	public void setProviderCodeName(String providerCodeName) {
		this.providerCodeName = providerCodeName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwUserRegistrationItemId))
			return false;
		VwUserRegistrationItemId castOther = (VwUserRegistrationItemId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getUserLogin() == castOther.getUserLogin()) || (this
						.getUserLogin() != null
						&& castOther.getUserLogin() != null && this
						.getUserLogin().equals(castOther.getUserLogin())))
				&& (this.getItemId() == castOther.getItemId())
				&& ((this.getItemProjectName() == castOther
						.getItemProjectName()) || (this.getItemProjectName() != null
						&& castOther.getItemProjectName() != null && this
						.getItemProjectName().equals(
								castOther.getItemProjectName())))
				&& ((this.getItemItemName() == castOther.getItemItemName()) || (this
						.getItemItemName() != null
						&& castOther.getItemItemName() != null && this
						.getItemItemName().equals(castOther.getItemItemName())))
				&& ((this.getClientName() == castOther.getClientName()) || (this
						.getClientName() != null
						&& castOther.getClientName() != null && this
						.getClientName().equals(castOther.getClientName())))
				&& ((this.getClientCode() == castOther.getClientCode()) || (this
						.getClientCode() != null
						&& castOther.getClientCode() != null && this
						.getClientCode().equals(castOther.getClientCode())))
				&& ((this.getClientCodeName() == castOther.getClientCodeName()) || (this
						.getClientCodeName() != null
						&& castOther.getClientCodeName() != null && this
						.getClientCodeName().equals(
								castOther.getClientCodeName())))
				&& ((this.getProviderName() == castOther.getProviderName()) || (this
						.getProviderName() != null
						&& castOther.getProviderName() != null && this
						.getProviderName().equals(castOther.getProviderName())))
				&& ((this.getProviderCode() == castOther.getProviderCode()) || (this
						.getProviderCode() != null
						&& castOther.getProviderCode() != null && this
						.getProviderCode().equals(castOther.getProviderCode())))
				&& ((this.getProviderCodeName() == castOther
						.getProviderCodeName()) || (this.getProviderCodeName() != null
						&& castOther.getProviderCodeName() != null && this
						.getProviderCodeName().equals(
								castOther.getProviderCodeName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getUserLogin() == null ? 0 : this.getUserLogin().hashCode());
		result = 37 * result + this.getItemId();
		result = 37
				* result
				+ (getItemProjectName() == null ? 0 : this.getItemProjectName()
						.hashCode());
		result = 37
				* result
				+ (getItemItemName() == null ? 0 : this.getItemItemName()
						.hashCode());
		result = 37
				* result
				+ (getClientName() == null ? 0 : this.getClientName()
						.hashCode());
		result = 37
				* result
				+ (getClientCode() == null ? 0 : this.getClientCode()
						.hashCode());
		result = 37
				* result
				+ (getClientCodeName() == null ? 0 : this.getClientCodeName()
						.hashCode());
		result = 37
				* result
				+ (getProviderName() == null ? 0 : this.getProviderName()
						.hashCode());
		result = 37
				* result
				+ (getProviderCode() == null ? 0 : this.getProviderCode()
						.hashCode());
		result = 37
				* result
				+ (getProviderCodeName() == null ? 0 : this
						.getProviderCodeName().hashCode());
		return result;
	}

}
